INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (1, 1, 1, false, 'https://nature.com', 'edelgardillo0', 'E2xJLlQ4', 'challenge', 'Game', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (1, 1, 1, false, 'http://ibm.com', 'llammerts1', 'Fk6CJym', null, 'Work', true);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (1, 1, 1, false, 'http://moonfruit.com', 'vlomath2', 'nUOAbT1KB', null, 'Social Media', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (1, 1, 1, false, 'http://last.fm', 'ebernardotti3', 'JCDYRQ5ia', 'monitoring', 'Entertainment', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (1, 1, 1, false, 'https://gravatar.com', 'stod4', 'TrrOasy7q', 'empowering', 'Work', true);

INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (2, 1, 2, false, 'https://yellowpages.com', 'porum0', '5W8Zvn0G', null, 'Work', true);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (2, 1, 2, false, 'https://vistaprint.com', 'efanshaw1', 'gNK59Dnib', 'well-modulated', 'Entertainment', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (2, 1, 2, false, 'http://hibu.com', 'pclemence2', 'Cx19G3iFy', 'algorithm', 'Game', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (2, 1, 2, false, 'http://chronoengine.com', 'lramlot3', 'JnnaJ2J7', 'holistic', 'Social Media', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (2, 1, 2, false, 'http://behance.net', 'kgrayshan4', 'ybYokE5', null, 'Work', true);

INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (3, 1, 3, false, 'http://yelp.com', 'rpiddington0', 'c7XFxR', 'bifurcated', 'Work', true);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (3, 1, 3, false, 'http://reuters.com', 'lbazell1', 'n8ipAO0nq', 'tangible', 'Work', true);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (3, 1, 3, false, 'http://about.me', 'dlewin2', 'CXumHxIW', null, 'Social Media', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (3, 1, 3, false, 'https://yale.edu', 'nkemet3', 'r1EnbQF', null, 'Work', true);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (3, 1, 3, false, 'https://usatoday.com', 'fgaither4', 'f67uEF1Bq', 'frame', 'Entertainment', false);

INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (4, 1, 3, false, 'http://oracle.com', 'pulyatt0', 'desGni', 'Reactive', 'Work', true);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (4, 1, 3, false, 'https://howstuffworks.com', 'umarcham1', 'TY1k9oPfmI', null, 'Entertainment', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (4, 1, 3, false, 'http://mapy.cz', 'neckh2', 'BLs6iww4', 'bifurcated', 'Game', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (4, 1, 3, false, 'http://bigcartel.com', 'lmcane3', '5pypFZD', null, 'Game', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (4, 1, 3, false, 'http://wiley.com', 'kfrankowski4', '1YkNKoWQE', 'circuit', 'Social Media', false);

INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (5, 2, 1, false, 'http://51.la', 'stitterington0', '1CCrlou', 'even-keeled', 'Game', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (5, 2, 1, false, 'https://delicious.com', 'jbabington1', 'ixGOq37w', null, 'Social Media', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (5, 2, 1, false, 'https://live.com', 'vsenescall2', 'a5YQwG', 'Switchable', 'Work', true);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (5, 2, 1, false, 'http://dailymotion.com', 'sreye3', 'jDvHlng', 'Total', 'Entertainment', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (5, 2, 1, false, 'https://slate.com', 'abatterbee4', 'Owtkr2X', null, 'Work', true);

INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (6, 2, 2, false, 'http://ameblo.jp', 'cluciano0', 'RM4lF45e9Th8', null, 'Game', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (6, 2, 2, false, 'http://studiopress.com', 'ttrythall1', 'p8KAE4v7', 'matrix', 'Work', true);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (6, 2, 2, false, 'https://parallels.com', 'gblunden2', 'MaglxKdJ5', 'well-modulated', 'Work', true);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (6, 2, 2, false, 'https://diigo.com', 'hloveridge3', 'yRVujYUcSV', null, 'Entertainment', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (6, 2, 2, false, 'https://princeton.edu', 'oelder4', 'yyiWZbs', 'Mandatory', 'Social Media', false);

INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (7, 2, 3, false, 'http://deviantart.com', 'kgrewer0', 'nd0yRH', 'throughput', 'Social Media', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (7, 2, 3, false, 'http://tinyurl.com', 'hbreckin1', 'vtyU2ScYM5y', 'pricing structure', 'Work', true);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (7, 2, 3, false, 'https://scribd.com', 'colivazzi2', 'Gx26uh9', null, 'Entertainment', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (7, 2, 3, false, 'https://earthlink.net', 'llailey3', '6whmJT6mF', 'heuristic', 'Game', false);
INSERT INTO credentials (user_id, organization_id, role_id, is_user_created, website, username, password, hint, category, require_master_password) VALUES (7, 2, 3, false, 'https://google.cn', 'pmatuska4', 'aG2m571C', null, 'Work', true);
